name: Build and Deploy to Azure Container App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login (Service Principal)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set environment variables from secrets
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
  

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to DockerHub
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/project1:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/project1:latest

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name hdp3ehrenili \
            --resource-group hdp3 \
            --image ${{ secrets.DOCKER_USERNAME }}/project1:latest
            --set-env-vars MONGODB_URI=${{ secrets.MONGODB_URI }}

